services:
    php:
        container_name: ${DOCKER_PROJECT_NAME}_php
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker/ImageMagick-6/policy.xml:/etc/ImageMagick-6/policy.xml
            # if you use supervisor
            - ./docker/php/supervisor/messenger-worker.conf:/etc/supervisor/conf.d/messenger-worker.conf
        build: ./docker/php
        depends_on:
            - mysql
            - redis
        networks:
            - app_network

    nginx:
        container_name: ${DOCKER_PROJECT_NAME}_nginx
        image: nginx:1.19
        restart: unless-stopped
        volumes:
            - ./docker/nginx/logs:/var/log/nginx
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
            - redis
        ports:
            - 127.0.0.1:${DOCKER_NGINX_PORT}:80
        networks:
            - app_network

    mysql:
        image: mariadb:10.5.2
        container_name: ${DOCKER_PROJECT_NAME}_mysql
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_DATABASE=${DOCKER_PROJECT_NAME}
        volumes:
            # - ./sql:/sql
            - ./docker/mysql/db:/var/lib/mysql
        ports:
            - 127.0.0.1:${DOCKER_DATABASE_PORT}:3306
        networks:
            - app_network

    redis:
        image: redis:6.0.10-alpine
        restart: unless-stopped
        container_name: ${DOCKER_PROJECT_NAME}_redis
        ports:
            - "6379:6379"
        command: redis-server --appendonly yes
        networks:
            - app_network


networks:
    app_network:
        driver: bridge
